name: One Manga Day
url: http://onemangaday.dexp.in
#markdown: redcarpet
markdown: kramdown
#highlighter: pygments
highlighter: rouge
#excerpt_separator: "\n\r\n"
permalink: /:categories/:title.html
include: ["*.ks"]
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  sass_dir: _includes/sass
  style: compressed
compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  comments: all
  endings: []
  profile: false
