name: One Manga Day
url: http://onemangaday.dexp.in
#markdown: redcarpet
markdown: kramdown
highlighter: pygments
#highlighter: rouge
#excerpt_separator: "\n\r\n"
permalink: /:categories/:title.html
include: ["*.ks"]
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
